
#image: rikorose/gcc-cmake:8
image: gcc:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - apt-get install cmake

stages:
  - build
  - test

build:linux:
  stage: build
  tags:
    - linux
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
  artifacts:
    paths:
      - build/chaos/libchaos.a
      - build/chaos/libchaos.so
      - build/tests/testchaos

test:linux:
  stage: test
  dependencies:
    - build:linux
  script:
    - cd build/tests
    - ./testchaos

