language: cpp

branches:
  only:
  - master
  - staging

os:
- linux
- osx

dist: trusty
sudo: false

compiler:
- gcc
- clang

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test

    packages:
    - cmake
    - cmake-data
    - gcc-5
    - g++-5
    - clang
    - libssl-dev
    - libsqlite3-dev
    - libpng-dev
    - libjpeg-dev
    - libwebp-dev

before_install:
- uname -a
- cmake --version
- if [ "$TRAVIS_OS_NAME" == "osx" -a "$CC" == "gcc" ]; then brew update; fi
- if [ "$TRAVIS_OS_NAME" == "osx" -a "$CC" == "gcc" ]; then brew install gcc5; fi
- if [ "$CC" == "gcc" ]; then export CC="gcc-5" CXX="g++-5"; fi
- echo $CC
- echo $CXX
- mkdir libchaos-build

install:
- cd libchaos-build
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then export CMAKE_INCLUDE_PATH="/usr/local/opt/openssl/include"; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then export CMAKE_LIBRARY_PATH="/usr/local/opt/openssl/lib"; fi
- cmake ..
- make testchaos

script:
- cd tests
- ./testchaos
