language: cpp

branches:
  only:
  - travis

os:
- linux
- osx

dist: trusty
sudo: false

compiler:
- gcc
- clang

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test

    packages:
    - cmake
    - cmake-data
    - gcc-5
    - g++-5
    - clang
    - libssl-dev
    - libsqlite3-dev
    - libpng-dev
    - libjpeg-dev
    - libwebp-dev

before_install:
- cmake --version
- if [ "$CXX" == "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
- mkdir libchaos-build

install:
- cd libchaos-build
- cmake ..
- make testchaos

script:
- cd tests
- ./testchaos

