language: cpp

os:
- linux
- osx

compiler:
- gcc
- clang

addons:
    apt:
        sources:
        - george-edison55-precise-backport
        - ubuntu-toolchain-r-test

        packages:
        - cmake
        - cmake-data
        - libssl-dev
        - gcc-4.9
        - g++-4.9
        - clang

before_install:

script:
- mkdir libchaos-build
- cd libchaos-build
- cmake ..

- make testchaos

- cd libchaos-build/tests
- ./testchaos

